name: Update Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh stats
        run: |
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=AlekseyGolovk0&layout=compact&theme=radical" > /dev/null
